export const wines = [{

    id: 1,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  }, {
    id: 2,
    imageUrl: '/assets/red-wine.jpg',
    progress: 64,
    label: 'Wine',
  }, {
    id: 3,
    imageUrl: '/assets/red-wine.jpg',
    progress: 16,
    label: 'Wine',
  }, {
    id: 4,
    imageUrl: '/assets/red-wine.jpg',
    progress: 32,
    label: 'Wine',
  }, {
    id: 5,
    imageUrl: '/assets/red-wine.jpg',
    progress: 95,
    label: 'Wine',
  }, {
    id: 6,
    imageUrl: '/assets/red-wine.jpg',
    progress: 75,
    label: 'Wine',
  }, {
    id: 7,
    imageUrl: '/assets/red-wine.jpg',
    progress: 2,
    label: 'Wine',
  }, {
    id: 8,
    imageUrl: '/assets/red-wine.jpg',
    progress: 42,
    label: 'Wine',
  }]
